### ISSUE TITLE
aliasStage (throttlingRateLimit, throttlingBurstLimit) setting has no effect

### ISSUE THREAD

**Issue by AliasIO** [serverless-heaven/serverless-aws-alias#182]
I'm trying to configure `throttlingRateLimit` and `throttlingBurstLimit` for the API stage using the `aliasStage` setting but deploying just sets these values to the defaults (10,000 and 5,000).

``` yaml
...
plugins:
  - serverless-aws-alias

provider:
  ...
  aliasStage:
    throttlingBurstLimit: 10
    throttlingRateLimit: 5

functions:
  init:
    ...
    aliasStage:
      throttlingBurstLimit: 10
      throttlingRateLimit: 5
```

I tried to debug the issue myself, from what I can see the generated CloudFormation template does seem to be correct:

``` json
{
  "stageResource": {
      ...
      "MethodSettings": [
        {
          "ThrottlingBurstLimit": 10,
          "ThrottlingRateLimit": 5,
          "ResourcePath": "/~1",
          "HttpMethod": "GET"
        }
      ]
    },
    ...
  }
}
```

To work around this I need to remember to manually change the values after each deployment. I don't think I'm doing anything wrong here, is it working for anyone else?

```
$ sls --version
Framework Core: 1.61.3
Plugin: 3.2.7
SDK: 2.3.0
Components Core: 1.1.2
Components CLI: 1.4.0
```

``` json
{
  "devDependencies": {
    "serverless-aws-alias": "^1.8.0"
  }
}
```

cc @HyperBrain #59
