### ISSUE TITLE
Alias not applied to event bridge events

### ISSUE THREAD

**Issue by Psycholive** [serverless-heaven/serverless-aws-alias#192]
When using eventbridge event for a lambda, the created rule refers to the lambda, not to the lambda alias.

```
functions:
  - xxx:
      handler: file.handler
       events:
        - eventBridge:
            eventBus: arn:aws:***
```

Target of created rule is `xxx`, not `xxx:alias`
