### ISSUE TITLE
How to spec alias name on yml file

### ISSUE THREAD

**Issue by yangyao** [serverless-heaven/serverless-aws-alias#199]
Like down below ?

```
functions:
  user:
    name: myFunc
    alias: dev
    handler: processor.handler
```

or 

```
functions:
  user:
    name: myFunc:dev
    handler: processor.handler
```

The second deploy fail
